### ISSUE TITLE
希望完善下MySQL语法的支持，不然大多数人都用不起来

### ISSUE THREAD

**Issue by h2ero** [lealone/Lealone-xSQL#2]
execute sql: SHOW VARIABLES
execute sql: SELECT @@global.max_allowed_packet
Failed to execute statement: SELECT @@global.max_allowed_packet
org.lealone.common.exceptions.DbException: Syntax error in SQL statement "SELECT @@GLOBAL.[*]MAX_ALLOWED_PACKET " [42000-0]
	at org.lealone.common.exceptions.DbException.get(DbException.java:173)
	at org.lealone.common.exceptions.DbException.get(DbException.java:150)
	at org.lealone.common.exceptions.DbException.getSyntaxError(DbException.java:185)
	at org.lealone.xsql.mysql.sql.MySQLParser.getSyntaxError(MySQLParser.java:530)
	at org.lealone.xsql.mysql.sql.MySQLParser.parse(MySQLParser.java:296)
	at org.lealone.xsql.mysql.sql.MySQLParser.parse(MySQLParser.java:179)
	at org.lealone.db.session.ServerSession.prepareStatement(ServerSession.java:465)
	at org.lealone.db.session.ServerSession.prepareSQLCommand(ServerSession.java:438)
	at org.lealone.xsql.mysql.server.MySQLServerConnection.executeStatement(MySQLServerConnection.java:180)
	at org.lealone.xsql.mysql.server.MySQLServerConnection.executeStatement(MySQLServerConnection.java:173)
	at org.lealone.xsql.mysql.server.handler.CommandPacketHandler.handle(CommandPacketHandler.java:46)
	at org.lealone.xsql.mysql.server.MySQLServerConnection.handle(MySQLServerConnection.java:335)
	at org.lealone.net.nio.NioEventLoop.read(NioEventLoop.java:207)
	at org.lealone.server.Scheduler.handleSelectedKeys(Scheduler.java:380)
	at org.lealone.server.Scheduler.doAwait(Scheduler.java:369)
	at org.lealone.server.Scheduler.executeNextStatement(Scheduler.java:211)
	at org.lealone.server.Scheduler.run(Scheduler.java:92)
Caused by: org.lealone.common.exceptions.JdbcSQLException: Syntax error in SQL statement "SELECT @@GLOBAL.[*]MAX_ALLOWED_PACKET "; SQL statement:
SELECT @@global.max_allowed_packet [42000-0]
	at org.lealone.common.exceptions.DbException.getJdbcSQLException(DbException.java:342)
	... 17 more

**Comment by codefollower** [comment]
mysql 的参数太多了，一时半会很难兼容它的所有语法，而且因为实现不同，mysql 的参数在 lealone 里面设置可能没有意义。

**Comment by h2ero** [comment]
直接返回个默认值就行，虽然无用，总比直接报错好。

**Comment by codefollower** [comment]
就算是个默认值，也要查 mysql 的文档确定返回的值是什么类型的，否则 mysql 的客户端还是可能会报错的。
不同的 mysql 客户端(包括 mysql 的 jdbc 驱动) 用了很多 mysql 的特殊语法来获取或设置参数值，
所以不兼容的地方更多的还是出在 mysql 的客户端。

lealone 的 sql 语法是继承自 h2 的，h2 的 dml 语句的语法其实跟 mysql 很接近的，
如果通过 lealone 的客户端 或者是 DBeaver 和 DataGrip 这类通过标准 jdbc 访问数据库的图形工具来读写 lealone，这时用 mysql  的 dml 语句的语法反而兼容性更好。

**Comment by codefollower** [comment]
如果是用 jvm 系的语言开发应用，我是直接推荐用 lealone 的 jdbc 驱动来访问 lealone 数据库，这时应用可以用 mysql 的语法，
也就是用 lealone jdbc 驱动 + mysql 语法 这个组合，性能比  mysql jdbc 驱动 好得多。

非 jvm 系的应用，只能用 mysql 客户端 + lealone xsql 这个组合了。

**Comment by codefollower** [comment]
如果是用 jvm 系的语言开发应用，我是直接推荐用 lealone 的 jdbc 驱动来访问 lealone 数据库，这时应用可以用 mysql 的语法，
也就是用 lealone jdbc 驱动 + mysql 语法 这个组合，性能比  mysql jdbc 驱动 好得多。

非 jvm 系的应用，只能用 mysql 客户端 + lealone xsql 这个组合了。

**Comment by h2ero** [comment]
ok, 后面有应用场景再试试看，今天只是想简单试用下。
